### ISSUE TITLE
Category buttons on the left become inaccessible when zoomed in or when using website in android.

### ISSUE THREAD

**Issue by NGB-Was-Taken** [Animeboynz/Mihon-Backup-Viewer#15]
For some reason you can't scroll to the left at all. You can scroll to the right fine though.

**Comment by Animeboynz** [comment]
I have fixed this on my break, Ill commit it after I finish work in about 4h

**Comment by Animeboynz** [comment]
Shit. My change made it so that it doesn't go past the screen but it also made the tab contents left aligned instead of centred. Ill leave it for now cus I hate that the buttons get hidden but I really want it to be centred.

What would be a good option to handle many categories. like 30-40+ do we add a scrollbar when there are too many? or automatically switch it to select box if it detects there are more than can fit on a screen.
![Screenshot 2024-06-16 210019](https://github.com/Animeboynz/Mihon-Backup-Viewer/assets/40583749/b2c9026a-ee75-488a-abb5-4dfb766a01d8)
